import { exec, slugify, REPO_DIR } from './utils.js';
import type { AgentIssue } from './types.js';

export function buildBranchName(issue: AgentIssue): string {
  return `agent/${issue.identifier.toLowerCase()}-${slugify(issue.title)}`;
}

export function setupBranch(branchName: string): void {
  exec('git checkout main');
  exec('git pull origin main');
  try { exec(`git branch -D ${branchName}`); } catch { /* didn't exist */ }
  try { exec(`git push origin --delete ${branchName}`); } catch { /* not on remote */ }
  exec(`git checkout -b ${branchName}`);
}

export async function publish(branchName: string, issue: AgentIssue): Promise<string> {
  const newCommits = exec(`git log main..${branchName} --oneline`);
  if (!newCommits) throw new Error('No commits on branch — nothing to publish');

  exec(`git push --force origin ${branchName}`);

  const githubToken = process.env.GITHUB_TOKEN;
  if (!githubToken) throw new Error('GITHUB_TOKEN environment variable is required');

  const prTitle = `${issue.identifier}: ${issue.title}`;
  const prBody = [
    '## Summary',
    '',
    `Implemented by dev agent from Linear issue [${issue.identifier}](${issue.url}).`,
    '',
    issue.description ?? '',
    '',
    '## Test plan',
    '- [ ] Review the code changes',
    '- [ ] Run tests locally',
    '- [ ] Test in browser',
    '',
    '🤖 Generated by SLApp dev agent',
  ].join('\n');

  const response = await fetch('https://api.github.com/repos/PepsSTP/SLApp/pulls', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${githubToken}`,
      Accept: 'application/vnd.github+json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ title: prTitle, body: prBody, head: branchName, base: 'main' }),
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`GitHub API error ${response.status}: ${text}`);
  }

  const pr = await response.json() as { html_url: string };
  return pr.html_url;
}
